### ISSUE TITLE
limited write ability planned?

### ISSUE THREAD

**Issue by i30817** [Ortham/esplugin#11]
I'd like to automate some tedious morrowind modding.

Namely i want to do a mod to turn every spell scroll into a (actual) new spell.

pseudo code:

```
for every esp or omwaddon:
     for scroll in 'sc_name' (added or override):
          if(scroll has enchantment and doesn't have a script) (it's a normal spell scroll)
               name_suffix = scroll.getName()[10..] ( 'Scroll of [name_suffix]')
               create new spell with name [Scribed [scroll_record]] and effects and costs the same as enchantment
               create script to learn the spell on equipping of the scroll
               add script as override for the scroll
               (scroll override, new spell) to overrides_list

      if (overrides_list not empty)
          create new compatibility omwaddon with overrides:
      
```  

Anyway, this  needs both a write capability and at least being able to get the names/enchantment/effects/costs of records. Is the project planning write capability? And if not, you know of a way i can program it? And reading these properties?

**Comment by Ortham** [comment]
I'm not going to add plugin writing to esplugin. It sounds like you might be able to write an xEdit script to do what you want.

**Comment by i30817** [comment]
xEdit both doesn't appear to have morrowind support and also doesn't appear to be able to be invoked from the cmd line (though i didn't really look further after the 'no morrowind support').

**Comment by Ortham** [comment]
My knowledge of Morrowind is very limited, I don't have another answer to give.
