### ISSUE TITLE
I don't understand how to use the library

### ISSUE THREAD

**Issue by alekcey0211** [Ortham/esplugin#29]
Sorry, I created a rust project, added the esplugin 3.4.0 dependency. But I don't understand how I can take any values from esp by FormID

My main.rs file
```rs
extern crate esplugin;

use esplugin::{GameId, Plugin};
use std::path::Path;

const PLUGIN_TO_PARSE: &str = "plugins/HIVE.esp";
const GAME_ID: GameId = GameId::SkyrimSE;

fn main() {
    let mut plugin = Plugin::new(GAME_ID, Path::new(PLUGIN_TO_PARSE));
    plugin.parse_file(false);
    let c = plugin.count_override_records();

    println!("Hello, world!");
    println!("{}", c);
    println!("{}", plugin.path().display());
}
```

Can you help me in discord or show examples.
Or am I just initially using your library incorrectly

**Comment by Ortham** [comment]
You can only get some limited information from the TES4 header. This isn't a general-purpose plugin parsing library.

**Comment by alekcey0211** [comment]
So I can't read the record data like in XEditLib or esper?

**Comment by Ortham** [comment]
No, you can't, that isn't implemented.

**Comment by alekcey0211** [comment]
thx
