### ISSUE TITLE
Extend range of supported light plugin FormIDs for Skyrim SE

### ISSUE THREAD

**Issue by Ortham** [Ortham/esplugin#40]
A new Skyrim SE [update](https://bethesda.net/en/article/4ORD7tshfmHUN8H4ULSgE4/the-elder-scrolls-v-skyrim-special-edition-creations-update-patch-notes) has expanded the range of supported light plugin FormIDs to 4096. 

The new plugins `_ResourcePack.esl` and `unockatja.esl` use the increased range and so currently appear invalid. `_ResourcePack.esl` has a HEDR version of 1.71, while older ESL plugins have a version of 1.70, which may be related (I don't have `unockatja.esl` to check it).

**Comment by pStyl3** [comment]
I have bought all of them now, `ccrs001.esl` also uses the increased range.

![grafik](https://github.com/Ortham/esplugin/assets/10406657/1ff9c504-51b8-4e12-8759-ba14d1e654f0)

**Comment by pStyl3** [comment]
```
_ResourcePack.esl

ccrs001.esl
unockatja.esl
cbgs_tdowwinterfrost.esp
ceejsse001_lodge.esp
kinggathcreations_eastempirecompany.esp
legendarydungeons-dwemer.esp
msjm01_arquebus.esp
```
All of these plugins have the HEDR version `1.71`.

**Comment by pStyl3** [comment]
![grafik](https://github.com/Ortham/esplugin/assets/10406657/4ab03239-c56e-4514-9266-9d390a9578d9)

**Comment by FlayaN** [comment]
Is it possible to update this for skyrim VR too? But extended formids is only available if you have the [Skyrim VR ESL Support](https://www.nexusmods.com/skyrimspecialedition/mods/106712) installed. Not sure if you can check for that.. Would be nice to get rid of the errors in LOOT 😄

**Comment by Ortham** [comment]
This library doesn't distinguish between Skyrim SE and Skyrim VR (I assumed that VR kept pace with SE), so I don't think any changes are necessary for that.
