### ISSUE TITLE
Fails to build on ARM

### ISSUE THREAD

**Issue by limo-app** [Ortham/esplugin#46]
When trying to build `esplugin` as part of `libloot` on ARM (aarch64) on a Linux system i get the following error:
```
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-gnu` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-gnu`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `memchr` (lib) due to 1 previous error
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-gnu` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-gnu`
```

The same error occurs during the build of `loot-condition-interpreter` and `libloadorder`. Building on x86_64 works fine in all 3 cases.

**Comment by Ortham** [comment]
Are you trying to build a native ARM library or cross-compile for x86_64 on ARM?

libloot's CMake config assumes that you're building for x86_64 if you're building on Linux, so if you're not trying to cross-compile then you'll need to change that: https://github.com/loot/libloot/blob/master/CMakeLists.txt#L65

**Comment by limo-app** [comment]
I am building natively on ARM, which means i should be fine as long as the `--target` option is not set for cargo. Would it be possible to add a CMAKE option to `libloot` that, when set, builds `esplugin`, `libloadorder` and `loot-condition-interpreter` without `--target`? According to the cargo build docs, this should always build natively. Seeing that this is what causes my problem, i should have opened this issue on the `libloot` page, sorry for that.

**Comment by Ortham** [comment]
I don't really want to add a specific config option, but I can improve the logic so it'll only set a target if it's identified a specific target is needed (i.e. avoid setting a target in an else block).

For now, just edit the CMakeLists to remove the target, and see how far that gets you - I wouldn't be surprised if other changes are necessary, because it's only been tested for x86 Windows, x86-64 Windows and x86-64 Linux.

**Comment by limo-app** [comment]
I will do that, thank you!

**Comment by Ortham** [comment]
I've made that change in https://github.com/loot/libloot/commit/6a5e96b5970097435bfe08260061d08b52e4a650, so closing this.
